import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>MovieDB</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className="root">
        <h1>Hello moviedb</h1>
      </main>
    </>
  )
}
